name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: submodules
      run: git submodule init && git submodule update
    - name: make
      run: make
    - name: make install
      run: make install
    - name: make install
      run: make check
